// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/action/action.proto)

#include "plugins/action/action_operators.h"

#include <cmath>
#include <limits>

namespace mavsdk {





} // namespace mavsdk